//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Templates", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;createRecord&quot;:
        ///	{
        ///		&quot;type&quot;:
        ///		{
        ///			&quot;id&quot;: &quot;Building-Electrical-Residential-NA&quot;
        ///		},
        ///		&quot;contacts&quot;:
        ///		[{
        ///			&quot;familyName&quot;: &quot;Johnson&quot;,
        ///			&quot;givenName&quot;: &quot;John&quot;,
        ///			&quot;tels&quot;: [
        ///				&quot;(415) 111-2233&quot;
        ///			],
        ///			&quot;emails&quot;: [
        ///				&quot;john@email.com&quot;
        ///			],
        ///			&quot;contactRole&quot;:
        ///			{
        ///				&quot;id&quot;: &quot;Building.cOwner&quot;
        ///			},
        ///			&quot;isPrimary&quot;: &quot;true&quot;,
        ///			&quot;entityState&quot;: &quot;Added&quot;
        ///		}],
        ///		&quot;asis&quot;: 
        ///		[{
        ///			&quot;id&quot;: &quot;BLD_RES_ELC&quot;,
        ///			&quot;subGroups&quot;: [
        ///				{
        ///					&quot;id&quot;: &quot;ELECTRIC.cSERVICE.cINFO&quot;,
        ///					&quot;items&quot;: [
        ///						{
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recordWithAsis {
            get {
                return ResourceManager.GetString("recordWithAsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;createRecord&quot;:
        ///	{
        ///		&quot;type&quot;:
        ///		{
        ///			&quot;id&quot;: &quot;Building-Electrical-Residential-NA&quot;
        ///		},
        ///		&quot;contacts&quot;:
        ///		[{
        ///			&quot;familyName&quot;: &quot;Johnson&quot;,
        ///			&quot;givenName&quot;: &quot;John&quot;,
        ///			&quot;tels&quot;: [
        ///				&quot;(415) 111-2233&quot;
        ///			],
        ///			&quot;emails&quot;: [
        ///				&quot;john@email.com&quot;
        ///			],
        ///			&quot;contactRole&quot;:
        ///			{
        ///				&quot;id&quot;: &quot;Building.cOwner&quot;
        ///			},
        ///			&quot;isPrimary&quot;: &quot;true&quot;,
        ///			&quot;entityState&quot;: &quot;Added&quot;
        ///		}]
        ///	}
        ///}.
        /// </summary>
        internal static string recordWithContact {
            get {
                return ResourceManager.GetString("recordWithContact", resourceCulture);
            }
        }
    }
}
